# Generated by Django 4.2.10 on 2025-04-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
