# Generated by Django 5.1.4 on 2024-12-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_rename_posted_at_job_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
