# Generated by Django 5.1.4 on 2024-12-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_remove_job_company_delete_company_delete_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
