# Generated by Django 5.1.4 on 2024-12-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company_remove_job_company_name_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=models.TextField(default='No requirements specified'),
        ),
    ]
